DROP USER TEST_USER CASCADE
/

CREATE USER TEST_USER IDENTIFIED BY test_password
/

GRANT CONNECT, RESOURCE TO TEST_USER
/

GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE SYNONYM TO TEST_USER
/

GRANT CREATE SESSION TO TEST_USER
/

GRANT UNLIMITED TABLESPACE TO TEST_USER
/

DROP USER OTHER_USER CASCADE
/

CREATE USER OTHER_USER IDENTIFIED BY test_password
/

GRANT CONNECT, RESOURCE TO OTHER_USER
/

GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE SYNONYM TO OTHER_USER
/

GRANT CREATE SESSION TO OTHER_USER
/

GRANT UNLIMITED TABLESPACE TO OTHER_USER
/
